### ISSUE TITLE
Release checklist for patch release v2.10.2

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/casper-client-sdk#226]
- [x] Close or defer all tickets in the epics (scope closure)
- [x]  Create release candidate branch (branching, tagging)
- [x]  Identify destination & distribution targets (communications, announcements)
- [x]  Ensure SRE pipelines are in place, including testing (testing evidence)
- [x]  Create readme in git repo (scope closure)
- [x] Ensure Changelog is in place 
- [x]  Documentation updates are in place (docs team); are we referring to the correct version throughout
