### ISSUE TITLE
JS-SDK release checklist

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/casper-client-sdk#233]
- [x] (DEV) Close or defer all tickets in the epics (code complete/scope closure) - code freeze
- [x]  (DEV) Create release candidate branch (branching, tagging)
- [x]  (Business Owner) Identify destination & distribution targets (communications, announcements)
- [x]  (SRE) Ensure SRE pipelines are in place
- [x]  (DEV) unit & Integration tests have passed
- [x]  (DEV) Create readme in git repo (scope closure)
- [x]  (DEV) ensure changelog is in place
- [x]  (SRE) acceptance tests in a production environment has passed ( N/A for JS SDK)
- [x]  (DEV) Documentation updates are in place (docs team)

**Comment by cspramit** [comment]
@hoffmannjan to tag the release and changelogs - then we are good release v2.11.0

**Comment by RitaMAllenCA** [comment]
@cspramit please close this ticket so i can close the release.  thanks!

**Comment by cspramit** [comment]
Released today all pending items closed
