### ISSUE TITLE
js-sdk release checklist

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/casper-client-sdk#271]
- [x] (DEV) Close or defer all tickets in the epics (code complete/scope closure) - code freeze
- [x]  (DEV) Create release candidate branch (branching, tagging)
- [x]  (Business Owner) Identify destination & distribution targets (communications, announcements)
- [x]  (SRE) Ensure SRE pipelines are in place
- [x]  (DEV) unit & Integration tests have passed
- [x]  (DEV) Create readme in git repo (scope closure)
- [ ]  (DEV) ensure changelog is in place
- [x]  (SRE) acceptance tests in a production environment has passed ( N/A for JS SDK)
- [ ]  (DEV) Documentation updates are in place (docs team)

**Comment by cspramit** [comment]
03/28 - All gating criteria met and released. However to add the sdk build zip to assets is in progress not a blocker.
